config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :events
  resources :places



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :text
#  date        :text
#  place_id    :integer
#  description :text
#  user_id     :integer
#  time_zone   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :place, :optional => true
end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id         :integer          not null, primary key
#  name       :text
#  facilities :text
#  event_id   :integer
#  time_zone  :integer
#  location   :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Place < ApplicationRecord
  has_many :events
  has_many :users, :through => :events
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  user_id         :integer
#  email           :text
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password
  has_many :events

validates :email, :presence => true, :uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


    before_action :fetch_user

    private
    def fetch_user
      @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
      session[:user_id] = nil unless @current_user.present? # This prevents horrors if you reseed.
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    current_user = User.find session[:user_id]
    @events = current_user.events
  end

  def new
    @event = Event.new
  end

  def create
    event = Event.create event_params
    place = Place.find params[:place_id]
    event.place_id = place.id
    event.save
    redirect_to event
  end

  def edit
    @event = Event.find params[:id]
  end

  def update
    event = Event.find params[:id]
    event.update event_params
    redirect_to event
  end

  def show
    @event = Event.find params[:id]
  end

  def add_place
   event = Event.find params[:id]
   place = Place.find params[:place_id]
   event.places << place
   redirect_to event
 end

  def destroy
    event = Event.find params[:id]
    event.destroy
    redirect_to event
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :user_id, :date, :place_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
   def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def create
    place = Place.create place_params
    # raise

    redirect_to place
  end

  def edit
    @place = Place.find params[:id]
  end

  def update
    place = Place.find params[:id]
    place.update place_params
    redirect_to place
  end

  def show
    @place = Place.find params[:id]

  end

  def add_event
   place = Place.find params[:id]
   event = Event.find params[:event_id]
   place.events << event
   redirect_to place
  end

  def destroy
    place = Place.find params[:id]
    place.destroy
     #binding.pry
    redirect_to place
  end

  private

  def place_params
    params.require(:place).permit(:name, :facilities, :event_id, :location)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
def new
end

def create
  @user = User.find_by :email => params[:email]
  if @user.present? && @user.authenticate(params[:password])
    session[:user_id] = @user.id
    flash[:notice] = "User created!"
    redirect_to root_path

  else
    flash[:error] = "Invalid email or password"
    redirect_to login_path
  end
end

def destroy
  session[:user_id] = nil
  redirect_to login_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path # it worked!
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <br>
    <%= f.label :title %>
    <%= f.text_field :title, :autofocus => true %>
  <br>
    <%= f.label :description %>
    <%= f.text_field :description %>
  <br>
    <%= f.label :date %>
    <%= f.date_field :date %>
  <br>
  <%= f.label :user_id %>
  <%= f.text_field :user_id, :value => session[:user_id] %>
  <br>

    <h3>Add Place</h3>
     <%= form_tag do %>
       <%= label_tag :name %>
       <%= select_tag :place_id, options_for_select(Place.pluck(:name, :id)), :include_blank => true, :required => true %>
        
       <a href="/places/new">New Place</a>
       <%= f.submit %>

     <% end %>


<% end %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render :partial => 'form' %>

app/views/events/index.html.erb
<h1>Events</h1>
<div class="events">
<% @events.each do |event| %>
  <ul>
    <li><%= link_to event.title, event %></li>
    <li><%= event.description %></li>
    <li><%= event.date %></li>
  </ul>
<% end %>
</div>

app/views/events/new.html.erb
<h1>Add a new event</h1>

<%= render :partial => 'form' %>

app/views/events/show.html.erb
<h1>Event</h1>
<div class="event">
<li><p>Title:   </p><%= @event.title %></li>
<li><p>Description:   </p><%= @event.description %></li>
<li><p>Date:   </p><%= @event.date %></li>

  <%# @event.place.each do |place| %>
  <% unless @event.place.name == nil || @event.place.name.empty? %>
  <li><%= link_to @event.place.name, @event.place %></li>
  <% end %>

</div>

<div class="controls">
  <%= link_to 'Edit', edit_event_path(@event) %>
  <%= link_to 'Delete', @event, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="nav">

              <ul>
                <li><%= link_to 'Home', root_path %></li>
                <li><% if @current_user.present? %>
                <%= link_to "Sign out #{ @current_user.email }", login_path, :method => 'delete' %>
                <% else %> &rarr;</li>
                <li><%= link_to 'Sign Up', new_user_path %></li>
                <li><%= link_to 'Sign In', login_path %>
                <% end %></li>
              </ul>

              <nav class="events-nav"><% if @current_user.present? %>
                <%= link_to 'All events', events_path %>
                <%= link_to 'New Event', new_event_path %>
                <%= link_to 'All places', places_path %>
                <%= link_to 'New Place', new_place_path %>
                <% else %></nav>
          <% end %>
          <% yield %>
      </div>

    </header>


    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Calendar</title>
  </head>
  <body>

  <div class="banner">
    <p>
      Keep record of everithing you need.
    </p>
  </div>

  <div class="content">
    <img src="http://people.oregonstate.edu/~calverta/calendar/beyond-cultural-competency-960px.png"></img>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
  nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
  esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
   sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>

  <footer>

  <div class="copyright">
    <p>&copy 2018</p>


  </div>
</footer>



  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <br>
    <%= f.label :name %>
    <%= f.text_field :name, :autofocus => true %>
  <br>
    <%= f.label :facilities %>
    <%= f.text_field :facilities %>
  <br>
    <%= f.label :Address %>
    <%= f.text_field :location %>
  <br>
  <!-- <%= f.label :user_id %> -->
  <!-- <%= f.text_field :user_id, :value => session[:user_id] %> -->
  <br>
    <%= f.submit %>

<% end %>

app/views/places/edit.html.erb
<h1>Edit event</h1>

<%= render :partial => 'form' %>

app/views/places/index.html.erb
<h1>My places</h1>
<div class="places">
<% @places.each do |place| %>
  <ul>
    <li><%= link_to place.name, place %></li>
    <li><%= place.facilities %></li>
    <li><%= place.location %></li>
  </ul>
<% end %>
</div>

<h3>My Google Maps Demo</h3>
 <!--The div element for the map -->
 <div id="map"></div>
 <script>
// Initialize and add the map
function initMap() {
// The location of Uluru
var uluru = {lat: -25.344, lng: 131.036};
// The map, centered at Uluru
var map = new google.maps.Map(
   document.getElementById('map'), {zoom: 4, center: uluru});
// The marker, positioned at Uluru
var marker = new google.maps.Marker({position: uluru, map: map});
}
 </script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwJ8kJwKTwMCvDECcZ3jQ6hRvzHQEb2sk&callback=initMap">
  </script>
</div>

app/views/places/new.html.erb
<h1>Add a new place</h1>

<%= render :partial => 'form' %>

app/views/places/show.html.erb
<h1>Selected place</h1>

<div class="place">
<li><p>Name:   </p><%= @place.name %></li>
<li><p>Facilities:   </p><%= @place.facilities %></li>
<li><p>Address:   </p><%= @place.location %></li>
</div>

<div class="placecontrols">
  <%= link_to 'Edit', edit_place_path(@place) %>
  <%= link_to 'Delete', @place, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
</div>

app/views/session/new.html.erb
<h2><%= flash[:error] %></h2>
<div class="log_in_form">
<%= form_tag login_path do %>
  <br>
    <div class="email">
      <%= label_tag :email %>
      <%= email_field_tag :email %>
    </div>
  <br>
    <div class="password">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
  <br>
    <%= submit_tag "Log in" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Get start with your calendar</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg.capitalize %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
  <br>

  <div class="name">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <br>

  <div class="email">
    <%= f.label :email %>
    <%= f.email_field :email, :required => true %>
  </div>

  <br>

    <div class="password">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <br>

  <div class="password_confirmation">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <br>

    <div class="buttom">
    <%= f.submit "Sign up!" %>
  </div>
<% end %>